ALTER TABLE hr_tasks DROP CONSTRAINT HR_Tasks_CreatedBy
ALTER TABLE hr_tasks DROP CONSTRAINT HR_Tasks_UpdatedBy

ALTER TABLE HR_Tasks WITH NOCHECK
ADD
    CONSTRAINT HR_Tasks_ParentTask
    FOREIGN KEY (ParentTask)
    REFERENCES HR_Tasks(Id)

ALTER TABLE HR_Tasks WITH NOCHECK
ADD
    CONSTRAINT HR_Tasks_AssignedTo
    FOREIGN KEY (AssignedTo)
    REFERENCES HR_Staff(Id)

ALTER TABLE HR_Tasks WITH NOCHECK ADD CONSTRAINT HR_Tasks_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES System_Users(Id)
ALTER TABLE HR_Tasks WITH NOCHECK ADD CONSTRAINT HR_Tasks_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES System_Users(Id)

ALTER TABLE HR_Tasks NOCHECK CONSTRAINT HR_Tasks_CreatedBy
ALTER TABLE HR_Tasks NOCHECK CONSTRAINT HR_Tasks_UpdatedBy