//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Weavver.Workflows
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WorkflowContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WorkflowContainer object using the connection string found in the 'WorkflowContainer' section of the application configuration file.
        /// </summary>
        public WorkflowContainer() : base("name=WorkflowContainer", "WorkflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WorkflowContainer object.
        /// </summary>
        public WorkflowContainer(string connectionString) : base(connectionString, "WorkflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WorkflowContainer object.
        /// </summary>
        public WorkflowContainer(EntityConnection connection) : base(connection, "WorkflowContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
