


-- GENERATE SQL THAT DROPS ALL CONSTRAINTS

SELECT 'ALTER TABLE ' + TABLE_SCHEMA + '.' + TABLE_NAME +
' DROP CONSTRAINT ' + CONSTRAINT_NAME
FROM information_schema.table_constraints
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
AND TABLE_NAME NOT LIKE 'aspnet_%'
ORDER by TABLE_NAME